FROM oven/bun:latest

WORKDIR /app

RUN apt-get update && apt-get install -y \
    sqlite3 \
    && rm -rf /var/lib/apt/lists/*

COPY package.json bun.lockb ./

RUN bun install

RUN mkdir -p src/public data logs

EXPOSE 3000

CMD ["bun", "run", "dev"]