services:
  zephyr-forge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zephyr-forge
    restart: unless-stopped
    ports:
      - "3456:3456"
    environment:
      - NODE_ENV=production
      - PORT=3456
      - HOST=0.0.0.0
      - SITE_URL=${SITE_URL:-https://forge.zephyyrr.in}
      - DOCS_URL=${DOCS_URL:-https://github.com/parazeeknova/zephyr}
    volumes:
      - sqlite-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3456/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  sqlite-data:
    name: zephyr-forge-data
