name: Publish to GitHub Packages

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@parazeeknova'

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Get version
        id: get_version
        run: echo "VERSION=$(bun x jq -r .version package.json)" >> $GITHUB_ENV

      - name: Publish to GitHub Packages
        run: |
          bun x jq --arg version "$VERSION" --arg name "@parazeeknova/zephyr-forge" \
            '.name = $name | .version = $version | .publishConfig.registry = "https://npm.pkg.github.com"' \
            package.json > temp-package.json
          mv temp-package.json package.json
          bun publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
