name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Update package.json for publishing
        run: |
          cp package.json package.json.orig
          jq '.publishConfig.registry = "https://registry.npmjs.org/"' package.json > tmp.json
          mv tmp.json package.json
          git add package.json package.json.orig

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bunx auto shipit

      - name: Restore original package.json
        if: always()
        run: |
          mv package.json.orig package.json
          git add package.json
          git commit -m "chore: restore package.json after release [skip ci]" || true
          git push
