name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Prepare package for publishing
        run: |
          # Copy necessary files to dist directory
          mkdir -p dist/bin
          cp -r bin/* dist/bin/
          cp package.json dist/
          cp README.md dist/
          
          # Update dist/package.json for NPM
          cd dist
          node -e "
            const pkg = require('./package.json');
            delete pkg.devDependencies;
            delete pkg.scripts;
            pkg.publishConfig = {
              registry: 'https://registry.npmjs.org/',
              access: 'public'
            };
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Setup .npmrc for publishing
        run: |
          cd dist
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Publish to NPM
        run: |
          cd dist
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
